services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_started

  celery:
    build: .
    command: celery -A core worker -l info
    volumes:
      - .:/app
      - ./backups:/backups
    env_file:
      - .env
    depends_on:
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_started
  
  celery-beat:
    build: .
    command: celery -A core beat -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  postgres-db:
    image: postgres:17
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
  
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped
  
volumes:
  postgres_data: