# Generated by Django 6.1 on 2026-08-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_namespace'),
    ]

    operations = [
        migrations.AddField(
            model_name='namespace',
            name='status',
            field=models.CharField(default='ready', max_length=20),
        ),
    ]
