# Generated by Django 6.1 on 2026-08-18 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_namespace_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255)),
                ('replicas', models.PositiveBigIntegerField(default=1)),
                ('container_port', models.PositiveIntegerField(blank=True, null=True)),
                ('cpu_request', models.CharField(blank=True, max_length=20)),
                ('cpu_limit', models.CharField(blank=True, max_length=20)),
                ('memory_request', models.CharField(blank=True, max_length=20)),
                ('memory_limit', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='resources.namespace')),
            ],
        ),
    ]
