# Generated by Django 6.1 on 2026-08-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='deletion_status',
            field=models.CharField(choices=[('not-deleted', 'Not Deleted'), ('terminating', 'Terminating')], default='not-deleted', max_length=20),
        ),
        migrations.AlterField(
            model_name='namespace',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('terminating', 'Terminating'), ('deleted', 'Deleted')], default='ready', max_length=20),
        ),
    ]
