# Generated by Django 6.1 on 2026-08-24 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_backupajob'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BackupaJob',
            new_name='BackupJob',
        ),
    ]
