# Generated by Django 6.1 on 2026-08-26 12:46

import resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_rename_backupajob_backupjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='backup_id',
            field=models.CharField(default=resources.models.generate_backup_id, editable=False, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='error',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
