# Generated by Django 6.0.8 on 2026-08-26 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('resources', '0008_backupjob_backup_id_backupjob_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupjob',
            name='error',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='PeriodicBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.TextField(max_length=250)),
                ('cron', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.app')),
                ('beat_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodicBackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resources.backupjob')),
                ('periodic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.periodicbackup')),
            ],
        ),
    ]
