# Generated by Django 6.0.8 on 2026-08-26 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_alter_backupjob_error_periodicbackup_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodicbackup',
            old_name='cron',
            new_name='schedule',
        ),
    ]
